General:
    dummy: False
AccessPoints:
    LocationOneWithCredentialAuth:
        ip: 127.0.0.1
        username: "username"
        password: "password"
        privatekeypath: ""
    LocationTwoWithKeyBasedAuth:
        ip: 127.0.0.1
        username: "username"
        password: ""
        privatekeypath: "./id_pub_rsa"